module.exports = {
  DEFAULT_MODEL_NAME: 'gpt-4.1',
  DEFAULT_OUTPUT_SUFFIX: '_annotated.txt',
  DEFAULT_CHUNK_TOKENS: 3200,
  DEFAULT_ANNOTATION_TEMPERATURE: 0.2,
  DEFAULT_VOCAB_MEMORY_PROMPT_LIMIT: 40,
  DEFAULT_VOCAB_MEMORY_STORE_LIMIT: 200,
  DEFAULT_FOOTNOTE_MARGIN_TOKENS: 500,
  DEFAULT_MIN_EFFECTIVE_CHUNK_TOKENS: 200,
  DEFAULT_TOKEN_COUNT_CACHE_SIZE: 4096,
  DEFAULT_KEEP_CHUNKS: false,
  DEFAULT_SHRINK_FACTORS: [0.9, 0.75, 0.6],
  DEFAULT_OPENAI_BASE_URL: 'https://api.openai.com/v1',
};
